services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: raa
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
